apiVersion: apps/v1
kind: Deployment
metadata:
  name: license-plate-recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: license-plate-recognition
  template:
    metadata:
      labels:
        app: license-plate-recognition
    spec:
      containers:
      - name: license-plate-recognition
        image: RegALPR.azurecr.io/license-plate-recognition:v1
        ports:
        - containerPort: 5000
