name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Login to Azure with Managed Identity
      run: |
        az login --identity

    - name: Set Kubeconfig
      run: |
        az aks get-credentials --name license-plate-aks --resource-group RG-ALPR

    - name: Apply Kubernetes Manifest
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
